---
- name: "Creating user prometheus"
  user:
    name: prometheus
    create_home: no

- name: "Downloading Prometheus"
  get_url:
    url: "{{ URL }}"
    dest: /home/


- name: "Extracting prometheus-*.tar.gz"

  unarchive:
    remote_src: yes
    src: /home/prometheus-{{ pro_version }}.linux-{{ arch }}.tar.gz
    dest: /home/


- name: "Moving extracted files to a folder prometheus-files"
  copy:
    remote_src: yes
    src: /home/prometheus-{{ pro_version }}.linux-{{ arch }}/
    dest: /home/prometheus-files/
    owner: prometheus
    group: prometheus

- name: "Copy prometheus from prometheus-files to /usr/local/bin/"
  copy:
    remote_src: yes
    src: /home/prometheus-files/prometheus
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755

- name: "Copy promtool from prometheus-files to /usr/local/bin/"
  copy:
    remote_src: yes
    src: /home/prometheus-files/promtool
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755

- name: "Configuring Prometheus to monitor itself"
  copy:
    src: prometheus.yml
    dest: /home/prometheus-files/
    owner: prometheus
    group: prometheus

- name: "Creating Prometheus Service File"
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
  register: prometheus_status

- name: "Restarting/Enabling Prometheus"
  #when: prometheus_status == true
  service:
    name: prometheus
    state: restarted
    enabled: true
