---
- name : "Installing Node Exporter"
  hosts: targets
  become: true
  vars:
    URL: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    ex_version: 1.3.1
    arch: amd64
  tasks:
    - include_tasks: node_exporter.yml
[root@ip-172-31-42-108 nodeexporter]# cd ..
[root@ip-172-31-42-108 prometheus]# cd server/
[root@ip-172-31-42-108 server]# l
-bash: l: command not found
[root@ip-172-31-42-108 server]# ll
total 28
-rw-r--r-- 1 root root  236 Jan  4 18:18 hosts
-r-------- 1 root root 1676 Jan  4 18:19 key.pem
-rw-r--r-- 1 root root  281 Jan  4 18:16 main.yml
-rw-r--r-- 1 root root 1460 Jan  4 18:16 prometheus_server.yml
-rw-r--r-- 1 root root  457 Jan  4 18:00 prometheus.service
-rw-r--r-- 1 root root  682 Jan  4 18:00 prometheus.yml
-rw-r--r-- 1 root root   33 Jan  4 18:00 README.md
[root@ip-172-31-42-108 server]# cat prometheus_server.yml
---
- name: "Creating user prometheus"
  user:
    name: prometheus
    create_home: no

- name: "Downloading Prometheus"
  get_url:
    url: "{{ URL }}"
    dest: /home/


- name: "Extracting prometheus-*.tar.gz"

  unarchive:
    remote_src: yes
    src: /home/prometheus-{{ pro_version }}.linux-{{ arch }}.tar.gz
    dest: /home/


- name: "Moving extracted files to a folder prometheus-files"
  copy:
    remote_src: yes
    src: /home/prometheus-{{ pro_version }}.linux-{{ arch }}/
    dest: /home/prometheus-files/
    owner: prometheus
    group: prometheus

- name: "Copy prometheus from prometheus-files to /usr/local/bin/"
  copy:
    remote_src: yes
    src: /home/prometheus-files/prometheus
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755

- name: "Copy promtool from prometheus-files to /usr/local/bin/"
  copy:
    remote_src: yes
    src: /home/prometheus-files/promtool
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755

- name: "Configuring Prometheus to monitor itself"
  copy:
    src: prometheus.yml
    dest: /home/prometheus-files/
    owner: prometheus
    group: prometheus

- name: "Creating Prometheus Service File"
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
  register: prometheus_status

- name: "Restarting/Enabling Prometheus"
  #when: prometheus_status == true
  service:
    name: prometheus
    state: restarted
    enabled: true
